# Generated by Django 3.1.7 on 2021-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=255)),
                ('numeroTarjeta', models.IntegerField(max_length=16)),
                ('fechaExpiracion', models.CharField(max_length=5)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
