# Generated by Django 3.1.7 on 2021-04-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210411_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nombreCiudad', to='api.ciudad'),
        ),
    ]
