# Generated by Django 3.1.7 on 2021-04-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210411_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='numeroTarjeta',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='adicion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modificador',
        ),
        migrations.RenameModel(
            old_name='adicion',
            new_name='grupo_modifica',
        ),
        migrations.CreateModel(
            name='unionModificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoModificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gruponombre', to='api.grupo_modifica')),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificadornombre', to='api.modificador')),
            ],
        ),
        migrations.CreateModel(
            name='conexionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productornombre', to='api.producto')),
                ('unionModificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nombreunion', to='api.unionmodificacion')),
            ],
        ),
    ]
