# Generated by Django 3.1.7 on 2021-04-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210412_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conexionproducto',
            unique_together={('producto', 'unionModificacion')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('categoria',)},
        ),
        migrations.AlterUniqueTogether(
            name='unionmodificacion',
            unique_together={('grupoModificador', 'modificador')},
        ),
    ]
