# Generated by Django 3.1.7 on 2021-04-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210412_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conexionproducto',
            options={'ordering': ['producto']},
        ),
        migrations.AlterUniqueTogether(
            name='unionmodificacion',
            unique_together=set(),
        ),
    ]
